Start.bat
dborodin836/TF2-GPTChatBot pull request #85
Opened 2024-01-07 16:24 UTC by teufortressIndustries

* FEAT: Added a bat file to simplify launching the script from the source.

I'm creating a one-click installer to simplify the process of the initial install.
The installer will detect the user's operating system and execute the required commands.

2024-01-08 13:02 UTC, dborodin836 commented
Thanks for the PR! This will be useful, especially for new users. I'll take a look and ensure compatibility across different operating systems. As far as I remember, there may be some issues with a Python package on platforms other than Windows, or maybe I'm just hallucinating.

2024-01-08 16:28 UTC, dborodin836 commented
Yeah, it seems that there are a few issues related to the stats functionality, stopping/starting the bot and the GUI.

2024-01-08 18:46 UTC, dborodin836 requested changes
Since the Linux version doesn't work properly, let's leave only the Windows .bat script and `one_click.py`. So, please remove any Linux-related stuff.

2024-01-08 18:46 UTC, dborodin836 commented on start.sh
Remove that file

2024-01-08 18:46 UTC, dborodin836 commented on start.bat
Rename the file to be more obvious for users `start.bat` -> `start_windows.bat`

2024-01-08 18:46 UTC, dborodin836 commented on one_click.py
> +    subprocess.run(command, shell=True)
That section doesn't seem to work on my system. Please try replacing it with the suggested code, delete the `venv` directory, and run the batch file again.
```
# execute the commands in a shell
subprocess.run(' & '.join(commands), shell=True)
```

2024-01-08 18:46 UTC, dborodin836 commented on one_click.py
> +    ]
Remove that section

2024-01-09 03:45 UTC, teufortressIndustries commented on one_click.py
> +    ]
Removed

2024-01-09 11:32 UTC, dborodin836 approved these changes
Looks good to me

2024-01-09 11:37 UTC, merged